# Point Config Server to your local Git repo (use absolute path)
spring.cloud.config.server.git.uri=file:///Users/abdulwahabshaik/Desktop/config-server-repo

# Run the Config Server on a different port (e.g., 8888)
server.port=8888

spring.application.name=configuration-server

# Eureka registration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Optional: show up quicker in dashboard
eureka.instance.lease-renewal-interval-in-seconds=5
eureka.instance.lease-expiration-duration-in-seconds=10