spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

server:
  port: 9090

eureka:
  client:
    service-url:
      defaultzone: http://localhost:8761/eureka/
