spring.application.name=first-client
spring.config.import=configserver:http://localhost:8888
spring.cloud.config.uri=http://localhost:8888

server.port=8081

# Eureka registration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Optional: show up quicker in dashboard
eureka.instance.lease-renewal-interval-in-seconds=5
eureka.instance.lease-expiration-duration-in-seconds=10