server.port=8080

spring.application.name=gateway_server
spring.config.import=configserver:http://localhost:8888

# Config Server URL
spring.cloud.config.uri=http://localhost:8888

# Eureka settings
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Enable Gateway discovery locator (for dynamic routing)
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Allow overriding beans if needed
spring.main.allow-bean-definition-overriding=true
