spring.application.name=eureka-server

# Port for Eureka server
server.port=8761

# OPTIONAL: Import configuration from Config Server (if used)
# You can keep it or remove it depending on if you're using a Config Server
spring.config.import=optional:configserver:http://localhost:8888

# Disable registration and fetching for Eureka Server (only clients do this)
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

eureka.client.service-url.defaultZone=http://localhost:8761

# Optional: faster status update in Eureka Dashboard
eureka.instance.lease-renewal-interval-in-seconds=5
eureka.instance.lease-expiration-duration-in-seconds=10
