spring:
  application:
    name: gateway
  config:
    import: "configserver:http://localhost:8888"
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

server:
  port: 8081

